const projectData = [
  {
    title: "Cv generator",
    description: "Create your cv and print it.",
    image: `${process.env.PUBLIC_URL}/assets/images/cv-image.png`,
    skill: "React",
    link: "https://daemne.github.io/cv-generator/",
    id: 1,
  },
  {
    title: "Calculator",
    image: `${process.env.PUBLIC_URL}/assets/images/calculator-image.jpeg`,
    description: "Simple calculator app.",
    skill: "Javascript",
    link: "https://daemne.github.io/calculator/",
    id: 2,
  },
  {
    title: "Rock paper scissors",
    image: `${process.env.PUBLIC_URL}/assets/images/rockPaperScissors-image.jpeg`,
    description: "Rock paper scissors, one of my first projects.",
    skill: "Html",
    link: "https://daemne.github.io/rock-paper-scissors/",
    id: 3,
  },
  {
    title: "Etch-a-sketch",
    image: `${process.env.PUBLIC_URL}/assets/images/etchASketch-image.jpeg`,
    description: "First project manipulating DOM with JavaScript.",
    skill: "Javascript",
    link: "https://daemne.github.io/etch-a-sketch/",
    id: 4,
  },
  {
    title: "Memory Game",
    image: `${process.env.PUBLIC_URL}/assets/images/memory-image.webp`,
    description:
      "Simple memory application using hooks and functional components.",
    skill: "React",
    link: "https://daemne.github.io/memory/",
    id: 5,
  },
  {
    title: "The Odin Project",
    image: `${process.env.PUBLIC_URL}/assets/images/theOdinProject-image.png`,
    description:
      "This repo contains all snippets of code I wrote in the last 5 months.",
    skill: "All",
    link: "https://www.github.com/daemne/theOdinProject",
    id: 6,
  },
  {
    title: "Admin Dashboard",
    image: `${process.env.PUBLIC_URL}/assets/images/adminDashboard-image.png`,
    description: "Created a simple admin dashboard.",
    skill: "Css",
    link: "https://daemne.github.io/admin-dashboard/",
    id: 7,
  },
  {
    title: "Library",
    image: `${process.env.PUBLIC_URL}/assets/images/library-image.jpeg`,
    description: "Add your books to a simple bookcase / library.",
    skill: "Javascript",
    link: "https://daemne.github.io/library/",
    id: 8,
  },
  {
    title: "Tic-tac-toe",
    image: `${process.env.PUBLIC_URL}/assets/images/ticTacToe-image.png`,
    description: "Play tic-tac-toe versus the computer.",
    skill: "Javascript",
    link: "https://daemne.github.io/tic-tac-toe/",
    id: 9,
  },
  {
    title: "Restaurant Menu",
    image: `${process.env.PUBLIC_URL}/assets/images/restaurantMenu-image.webp`,
    description: "First attempt at a bigger project.",
    skill: "Javascript",
    link: "https://daemne.github.io/restaurant-menu/",
    id: 10,
  },
  {
    title: "Weather display",
    image: `${process.env.PUBLIC_URL}/assets/images/weatherDisplay-image.jpeg`,
    description: "Api key currently not active",
    skill: "Javascript",
    link: "https://daemne.github.io/weather-display/",
    id: 11,
  },
  {
    title: "Form validation",
    image: `${process.env.PUBLIC_URL}/assets/images/formValidation-image.png`,
    description: "This page contains a simple form.",
    skill: "Javascript",
    link: "https://daemne.github.io/form-validation/",
    id: 12,
  },
];

export default projectData;
